### ISSUE TITLE
Investigate new SCM API for better integration

### ISSUE THREAD

**Issue by OpenNingia** [OpenNingia/vscode-clearcase#10]
Visual Studio code introduced a way to integrate SCM other than GIT, we should investigate if it is possible to integrate Clearcase with these new API, however:

1. Official documentation is still missing
2. The way Clearcase operate is pretty unique ( files being read-only before the checkout is something I never saw in other SCM )
3. Is this integration actually more productive than the one we already have?

References:
https://github.com/Microsoft/vscode/pull/15894
https://github.com/Microsoft/vscode/issues/15246

**Comment by jsinger67** [comment]
I created a separate extension that uses the new Source Control API. I used some snippets from the official Git SCM and it naturally integrates the same way as Git SCM does.

This extension is currently very basic and could be seen as a showcase or a starting point.
If you like please have a look at [vscode-clearcasescm](https://github.com/jsinger67/vscode-clearcasescm)
For me it was easier to create this from scratch than to change your existing extension although I know that this will impose additional effort to bring both together.

Note that I am very new to TypeScript :-).

This extension can be installed for testing side-by-side with your extension without problems.
Or you can simply run it in an extension host.

**Comment by OpenNingia** [comment]
Good job! I'll take a look at you code asap.

**Comment by Joinyy** [comment]
Is this still being developed?

**Comment by OpenNingia** [comment]
I'm mostly using git at work now and so I don't actively work on this project anymore. However I'm still here and can help or merge pull requests if needed.

**Comment by fr43nk** [comment]
I already made some changes to work with the new api. So there should be a new version soon.
@jsinger67 maybe we can combine your version with this one here as next step.

**Comment by OpenNingia** [comment]
I close this issue since the PR about SCM api is now merged
