### ISSUE TITLE
Annoyance: Error notifications for none-ClearCase files

### ISSUE THREAD

**Issue by arielgee** [OpenNingia/vscode-clearcase#106]
Hi,

The extension pops-up an error notification for any file that is not in ClearCase.
> _cleartool: Error: Cannot get view info for current view: not a ClearCase object_ 

I often use VS Code to open files that are not meant to be in ClearCase or I use other source control applications. 

Wouldn't it be best to detect whether the file in question is in a VOB prior to the execution of cleartool?

If that's problematic then maybe a setting that will define the paths for which the cleartool execution is allowed. Prevents redundant process executions and avoid the notifications.

Extension version: v4.1.0
VS Code version: 1.69.2 (Commit: 3b889b090b5ad5793f524b5d1d39fda662b96a2a, Date: 2022-07-18T16:12:52.460Z)
OS version: Windows_NT x64 10.0.19041

**Comment by fr43nk** [comment]
Hi,
I will take a look at this issue.

**Comment by fr43nk** [comment]
Could you please offer some more information about your setup?
Are you working in a workspace? Is this a clearcase view?

**Comment by arielgee** [comment]
Hi,

> Are you working in a workspace? Is this a clearcase view?

The ClearCase server is a remote LInux.
The VOBs view is mounted on my Windows client as an additional drive and is configured as a dynamic view.

**Comment by fr43nk** [comment]
It sounds the same like I work. When does this error message occur? Does it popup when you just opening a file or if another action is started?

**Comment by arielgee** [comment]
With VSCode I generally work with a folder and not a workspace.

The most basic scenario is to open VSCode on an empty folder without loading any file.
![image](https://user-images.githubusercontent.com/5435780/182310973-f9d11468-a0d9-4c32-a1d0-164a1c2ba9ba.png)

Also if you open 2-3 new empty text files from the 'File' menu and then switch between them. The notification popup repetitively for each file.

**Comment by fr43nk** [comment]
Ok, thank you. Now I can reproduce the issue.
