### ISSUE TITLE
ClearCase menu entries appear in OUTPUT window

### ISSUE THREAD

**Issue by BillDenton** [OpenNingia/vscode-clearcase#15]
ClearCase menu entries (Checkout, Checkin, Undo Checkout, Compare with previous version, Version tree) appear in right click menu in OUTPUT window. Not expected as OUTPUT window doesn't contain a file. Other menu entries such Go To Definition, etc. only appear in file windows.

**Comment by OpenNingia** [comment]
I can reproduce this on my installation.

@fr43nk this seems related to #14 , can you check?

**Comment by fr43nk** [comment]
Ok, will take a look at this. This was something I did not test or even think it could work :)

**Comment by OpenNingia** [comment]
This is be fixed in 1.9.0.

**Comment by BillDenton** [comment]
Confirmed fixed in 1.9.0
