### ISSUE TITLE
Strange scrolling issue

### ISSUE THREAD

**Issue by annab123081** [OpenNingia/vscode-clearcase#154]
On some files, when I type, for every keystroke the file scrolls down one. This includes using keyboard shortcuts or backspacing. It's strange, but I'm pretty confident that it's caused by this extension. When I disable the extension, it goes away, and when I re-enable, it's back. Others on my team have noticed the problem on their computers as well. It won't always happen when I'm typing on the top of the file but will start by at least line 15. I can delete everything that was in the file, and the problem will still persist in the blank file. 
This has only affected 2 files in my project of about 100 files, so it's not a widespread problem. I just wanted to report it in case anyone else runs into this.

**Comment by fr43nk** [comment]
Hi,
sounds really strange. To make a first guess: Is the annotation feature activated?

Best,
Frank

**Comment by annab123081** [comment]
Yes, you were right. Disabling the annotation feature fixed it. That's so much easier than uninstalling the extension when I need to edit that file. Thanks!

**Comment by fr43nk** [comment]
Ok, cool. Nevertheless I will try to fix this issue. Perhaps there is an easy reason for this. 

Thanks,
Frank
