### ISSUE TITLE
Annotation code-lens is always enabled

### ISSUE THREAD

**Issue by OpenNingia** [OpenNingia/vscode-clearcase#18]
The "Toggle Annotation" code lens activates even when the opened file is not a clearcase object.
This is strange because I was under the impression that the whole extension was not activated if the workspace is not a clearcase vob.

**Comment by fr43nk** [comment]
Ok, I think there is something missing checking before creating the code lens. I will take a look at this.

**Comment by fr43nk** [comment]
Please have a look at #19

**Comment by jimmy0415** [comment]
Could I please ask how I can turn off ""Toggle Annotation""?
Many thanks!

**Comment by OpenNingia** [comment]
Fixed with 6d1ebe722e2f454cbfdb7d3da07d9ee36ba1050e

**Comment by OpenNingia** [comment]
@jimmy0415 with version 1.11.0 there is a configuration parameter to toggle the annotation code lens: `vscode-clearcase.showAnnotationCodeLens`
