### ISSUE TITLE
Statusbar commands

### ISSUE THREAD

**Issue by fr43nk** [OpenNingia/vscode-clearcase#21]
I'm thinking about adding some commands to the statusbar version information.
This can simply be accomplished by assigning a command to the statusbar item, like
```
this.m_statusbar.command = "extension.ccStatusbarCmd"
``` 
When someone clicks the button, a quick pick list can be shown.
There such things as ```open in clearcase explorer``` or ```compare to previous version``` etc. can be listed.

What do you think about it?

**Comment by OpenNingia** [comment]
I probably won't use it since I'm used to the keyboard shortcuts, but it's still an interesting feature. As long as it works and it's not too invasive I'm not opposed :)

**Comment by fr43nk** [comment]
If you have time, you can take a look at this :)

https://github.com/fr43nk/vscode-clearcase/tree/feature/statusbar_command
Feel free to comment.

**Comment by OpenNingia** [comment]
![image](https://cloud.githubusercontent.com/assets/184624/24346347/3068df76-12d4-11e7-888b-460b02f5f961.png)

I tried it and works as expected, but are the internal command name supposed to be printed alongside the label? ( see image )
