### ISSUE TITLE
Command Failed Error for Toggle Annotations

### ISSUE THREAD

**Issue by jeremytam** [OpenNingia/vscode-clearcase#23]
Hi there; the "Toggle Annotations" tab keeps appearing for this embedded ClearCase error - it keeps disappearing and reappearing making my code jump every few lines I write. Has anyone seen thie "use no checkouts option" error?

![cc_vs_annot_error](https://cloud.githubusercontent.com/assets/7294127/25134225/0c84f1bc-241d-11e7-9eb1-2f75728485ff.png)

**Comment by OpenNingia** [comment]
This is a known limitation, because clearcase doesn't allow to annotate a checked-out file.
If you pass the `–nco` parameter to the `cleartool annotate` command it just annotate the previous version which probably differ from the checked out one ( thus making the annotated scrambled ).

**Comment by BillDenton** [comment]
Just had the same problem. Would it be possible to detect this error condition and issue a more informative error message?
