### ISSUE TITLE
vscode-clearcase.showVersionInStatusbar false doesn't disable the version info in status bar

### ISSUE THREAD

**Issue by BillDenton** [OpenNingia/vscode-clearcase#26]
vscode-clearcase.showVersionInStatusbar false doesn't disable the version info in status bar. I think it used to work. I disable this information as it uses a lot of space in the status bar.

**Comment by OpenNingia** [comment]
I just checked and, I still don't know why, but it works if you toggle the flag in the settings (set it to true, save, then to false, save). It doesn't work when the extension is loaded thou.

**Comment by BillDenton** [comment]
Seems to work after reloading the window. If it is on (true) and then you set to off (false) the version information changes to [view private] before reloading the window. After reloading the window the information disappears completely.
