### ISSUE TITLE
Show version information on hover over file tab top

### ISSUE THREAD

**Issue by BillDenton** [OpenNingia/vscode-clearcase#27]
Instead of showing version information in the status bar, how about showing it in the hover over on the file name at the top of the tab. VS Code shows the full path filename at the moment. Would it be possible to add the version information below the filename? This would provide the information without occupying valuable space on the status bar.

**Comment by OpenNingia** [comment]
need to investigate this if possible. I especially like the suggestion because I would like to use the statusBar for something else ( current activity )

**Comment by fr43nk** [comment]
Currently vscode does not support to directly change the title of a editor tab. So implementing this isn't possible right now
