### ISSUE TITLE
Default Checkout Comment

### ISSUE THREAD

**Issue by stuartjsmith** [OpenNingia/vscode-clearcase#28]
My organisation requires that we provide a checkout comment - we would like the ability to specify a default check out comment in the settings, and this to then be shown in the check out dialog box. From the command line it's just the -c option, so hopefully something similar is possible via the UI.

**Comment by OpenNingia** [comment]
The current implementation rely on the `cleardiag` tool that does indeed have a `/comment` option.
Unfortunately using that option as a side effect; if there is a current activity and you supply the `/comment` parameter then the checkout is performed without showing the dialog.

This is nice and all but it changes the whole workflow (what if you wanted to change the activity?).

**Comment by quasarea** [comment]
Would be possible to expose this as a configurable property? I mean src/clearcase.ts
`exec("cleardlg /checkout \"" + path + "\"", (error, stdout, stderr) => { this.m_updateEvent.fire();}`

If "cleardlg /checkout" would be configurable I could have workaround.

**Comment by OpenNingia** [comment]
036361a8b46f008b144891da69b2ade30f62b910 should've fixed this. Can anyone confirm?
