### ISSUE TITLE
Compare with previous version using visual studio code diff engine

### ISSUE THREAD

**Issue by quasarea** [OpenNingia/vscode-clearcase#29]
Could it be that 'compare to previous version' utilises vs diff rather than clearcase diffmerge?

**Comment by OpenNingia** [comment]
Added in version v2.1.0 ( limited to checked out files, is that ok ? )

**Comment by bw1faeh0** [comment]
You can set the default file compare tool:
In `\IBM\RationalSDLC\ClearCase\lib\mgrs\map` all tools are configured. You have to change line 7 from
`text_file_delta		xcompare			..\..\bin\cleardiffmrg.exe`
to a tool, you would like. 
Problem:
This file only accepts one argument. This means: `\path\to\code.exe` works, but not `\path\to\code.exe --diff`. You have to write a wrapper, that takes to arguments (two files) and calls `\path\to\code.exe -diff file1 file2`.
