### ISSUE TITLE
Feature requests: Open Properties of View, Find Modified Files and Update View

### ISSUE THREAD

**Issue by BillDenton** [OpenNingia/vscode-clearcase#3]
Please add  open Properties of View, Find Modified Files and Update View.
These would be nice commands to have. I don't use them as often as the commands that are already implemented. Thanks.

**Comment by OpenNingia** [comment]
Properties of View and Update View doesn't really make sense in a VSCode workspace ( at least I'm not opening the whole view all the times but only a subfolder ).

I can add a "Clearcase: Item Properties" and "Clearcase: Update folder" but they are going to be relative to the workspace directory ( same as Find Checkout / Find modified files )
