### ISSUE TITLE
Linux support

### ISSUE THREAD

**Issue by preiter** [OpenNingia/vscode-clearcase#30]
This extension isn't working for me on Linux.

Diff, undo checkout and version tree work
Annotation works
Checkin / Checkout do not work, they don't do anything

**Comment by OpenNingia** [comment]
The extension uses cleardlg executable to perform checkins and checkouts. I fear that it is not available on Linux.
Do you know of any Linux counterparts?

**Comment by preiter** [comment]
Suggestion: add configuration settings for the command that is bound to each feature. Then the user can override the cleardlg call with whatever they want.

Personally, I never use comments on my checkouts, so I would bind the checkout feature to

"vscode-clearcase.checkoutCommand":  "cleartool co -nc ${filename}"


As a refinement on this, if the user included a variable in their binding, like...

"vscode-clearcase.checkoutCommand":  "cleartool co -comment ${comment} ${filename}"

then you could prompt for a comment string.

**Comment by OpenNingia** [comment]
I thought of that one, however "cleartool co"  won't let you choose or
create an activity. So we would also need a "select current activity" and
"create new activity" commands.

Il sab 10 mar 2018, 23:55 preiter <notifications@github.com> ha scritto:

**Comment by preiter** [comment]
That's not necessarily an issue in Linux.

Typically you set a view and activity in a shell and then launch the editor from that shell.

The editor process inherits the selected view and activity from the shell that launched it, so there's no need for a command inside the editor to set the activity.

**Comment by OpenNingia** [comment]
I published a new version with the option to disable ClearDlg and use cleartool co / ci commands. Feedbacks are welcome.

**Comment by preiter** [comment]
Works great. Nice work.

**Comment by OpenNingia** [comment]
Wonderful! I'm closing this issue then. Fixed with 036361a8b46f008b144891da69b2ade30f62b910

👍
