### ISSUE TITLE
Editor scrolls whyle typing - showAnnotationCodeLens = false solves it.

### ISSUE THREAD

**Issue by Joinyy** [OpenNingia/vscode-clearcase#31]
Hi there,

While searching for a solution I found this issue:
https://github.com/Microsoft/vscode/issues/25402
There it is mentioned, that the scrolling while typing bug happens only with Code-Lense on. Therefore I disabled all Code-Lense features from every extension I had separately and the clearcase extension was the evil guy.

It is reproducible on several PCs with C-Code. I turned Code-Lense on for everything except clearcase then it works as intended. When turning on "vscode-clearcase.showAnnotationCodeLens" it is scrolling down while typing text.

**Comment by OpenNingia** [comment]
The upstream bug is closed, should I close this one too?
