### ISSUE TITLE
Add "ignore" filter on the SCM view private list

### ISSUE THREAD

**Issue by BillDenton** [OpenNingia/vscode-clearcase#37]
From issue #36.
The "VIEW PRIVATE" list in the "SOURCE CONTROL" tab is showing a lot of files that should be ignored. For example, I can see the .vscode directory, many ".obj, .exe, .bak" files and many.
I've noticed there is a "View Private File Suffixes" (defaulting to "(hh|cpp|def|c|h|txt)$"). However, is still showing a lot of other files (e.g. .obj, .exe, .bak, .vscode directory). I'm not sure how

**Comment by BillDenton** [comment]
I think the problem may have been fixed by the latest update (or maybe the reload of VS Code as part of the update). I can no longer see a huge list of files. When I add another file which should be under source control (in this case a ".cpp" file) it appears in the view private list.
However, I've just tried another instance of VS Code on another ClearCase view and it is showing unexpected view private files (view.stg, .pid, view_db.state, vista.taf). So maybe there still an issue.

**Comment by BillDenton** [comment]
There seems to something wrong with the "View Private File Suffixes" filter. I updated the filter to include py (python) and some other stuff. I added a ".py" file and it correctly appeared in the list. After renaming to "<original name>.py1" it is still in the list. As the filter is "(hh|cpp|def|c|h|txt|module|opt|py)$" I wouldn't expect ".py1" to appear. I would also suggest you add "py" to the list.

**Comment by BillDenton** [comment]
After deleting the ".py1" file the directory that it was in is now showing as checked out. Opening the version tree for the directory doesn't show the directory as checked out.

**Comment by BillDenton** [comment]
I've just done a build and files generated by the build and directories touched by the build are appearing. Reloading the window clears the view private list.

**Comment by fr43nk** [comment]
Hi
The view private topic is a bit tricky to handle with clearcase. 
First question: is it a snapshot or a dynamic view?
The list is refreshed once when the plugin is loaded and after that only triggered on checkin/checkout/save
So, i have registered an event for file create, change & delete within the workspace but it might not always work (for me I use dynamic views a lot, the events  do not fire) 
What about having a button which refreshes the file list in the scm view? 
I will investigate the filter and why it shows files not part of the regexp.

thanks

**Comment by fr43nk** [comment]
Hi,
I set a pull request (#38) regarding this issue #37. 
There was a missing filtering in the file event handling method. So every new or changed file was added to that list.

**Comment by BillDenton** [comment]
It a snapshot view. I always use snapshot views for development as the dynamic views are far too slow.

**Comment by fr43nk** [comment]
So perhaps you can help me: 
What command do you use to find view private files starting from the route of your snapshot view?
doing an
`ct ls -view_only -short -r .`
does not work, because the root is not an VOB. But my Workspace is set to the root of my snapshot view.

**Comment by BillDenton** [comment]
We have a python script to find view private files that appears to use "cleartool ls -recurse -nxn -view_only". Maybe it will work correctly once the changes from @fr43nk's pull request are released. At the moment I'm seeing lots of files that I would expect to be filtered out by the "View Private File Suffixes". Possibly directory filter would also be useful. However, if there are few incorrect files in the "VIEW PRIVATE" it will be fine.

**Comment by fr43nk** [comment]
Ok, so maybe it is usefull making the view private search command configurable?
If so, you could setup your python script to be started by the extension and its output can be inserted into the scm untracked file list?
What do you think about that? @OpenNingia

**Comment by BillDenton** [comment]
I'm not sure. It may be a bit too complex as the output of the configurable command has to be compatiable the extension. I think provided the "View Private File Suffixes" works and possibly a directory filter or a more sophisticated filter that can do the whole filename. To be honest, as long as the "VIEW PRIVATE" list isn't too long I don't care. Especially as we should be moving to git within 3 months.

**Comment by BillDenton** [comment]
I think the ClearCase extension is now slowing down the editor during builds. When I run a build (which I run in the terminal window using custom build task) it very difficult to edit files. It used to be fine. I think the view private file list is causing a problem because it can grow to over a thousand entries.

**Comment by fr43nk** [comment]
It would be interesting how the fixed version does affect the editor speed.
If it still does slow down VSCode then an option would be usefull to deactivate the file system events to prevent the update of the file list during build.

**Comment by BillDenton** [comment]
I've had to disable the extension. The builds are now not slowing down the whole Windows PC. I'll try again once @fr43nk 's changes are released.

**Comment by OpenNingia** [comment]
I made a few attempt but searching for private files is very slow, especially on snapshot views. I think that we need to disable the automatic refresh. Maybe it is enough to manually trigger the search when needed.

**Comment by fr43nk** [comment]
Ok, i will do that and provide a fix for that.

**Comment by OpenNingia** [comment]
I'm also experimenting with https://www.npmjs.com/package/ignore to add a .ccignore file using the .gitignore syntax as suggested.

**Comment by fr43nk** [comment]
Sounds nice. And also much more common.
Is it ok, that I do it?

**Comment by OpenNingia** [comment]
yes, feel free to submit any PR

**Comment by fr43nk** [comment]
I played a bit with that. One problem is in a multifolder workspace:
* is it needed to have one .ccignore file in every workspaceFolder?
* if no file is found, what is the default behavior?

**Comment by OpenNingia** [comment]
Yes, multifolder workspace is quite easy to implement. Each workspace has it's own .ccignore. When I played with it I did somethink like this:

```typescript
  public async findUntracked(folder: Uri): Promise<string[]> {
    let results: string[] = [];
    try {

      let ccIgnoreContent = await fsPromise.readFile(join(folder.fsPath, ".ccignore"));        
      let ccIgnore = ignore().add(ccIgnoreContent.toString());
```

In case of no ".ccignore" we can decide either to:

1. Having no filter
2. Use $HOME/.ccignore if it exists
3. Use a default filter

to me all of three options are good enough. At the end you'll want to have your own .ccignore anyway.

**Comment by fr43nk** [comment]
Ok, I did this the same way.
I think, just ignoring the view private files if no .ccignore file is found is the best solution. It avoids getting a very long file list in the scm view.

**Comment by fr43nk** [comment]
I still have some trouble understanding how the .ccignore file works. Do you know if it is possible to ignore all files except some specific ones?
I tried something like:
```
*
!*.cpp
!*.hh
```
But it doesn't work, all files are ignored.

**Comment by OpenNingia** [comment]
mh that would be a whitelist, .(git)ignore is a blacklist. So everything is accepted but the one that matches the .(git)ignore pattern.

**Comment by fr43nk** [comment]
Ah, ok, so this is my fault.
 :smile:

**Comment by OpenNingia** [comment]
I think that changes the .ccignore file should be automatically reflected. I means, it should not trigger a new "cleartool lsprivate" but only re-applying the filter to the existing list.
We may need to store the unfiltered list in memory.

**Comment by fr43nk** [comment]
Sounds interesting. I have to test how much the memory impact is in that case.
Adding the file event should be no problem.

**Comment by fr43nk** [comment]
As a first step, I created and filesystem event handling for .ccignore files.
@OpenNingia would you mind to test my version? Or should I create a pull request?
My branch is
`https://github.com/fr43nk/vscode-clearcase/tree/fix/issue-37-03`

Next step would be storing the whole file list and filter immediately.

**Comment by OpenNingia** [comment]
Ok, this is done so I'm closing it. In case of any bugs let's open a separate issue.
