### ISSUE TITLE
Adding mkelem command

### ISSUE THREAD

**Issue by fr43nk** [OpenNingia/vscode-clearcase#39]
When using the non dialog cleartool command the `checkin` command does not automatically create a versioned element of a view private element.
There are two new options:
* create a new command the user can call to start the `mkelem` command
* if configured, automatically create a versioned element if necessary. 

What do you think?

**Comment by OpenNingia** [comment]
it's a good idea. I was also thinking that we're going to need a way to:

1. show somewhere the current activity ( status bar? )
2. change the current activity ( select from the list )
3. create a new activity

if you're not going to use the clearcase's native dialogs you're going to need all of these ( and probably more )

**Comment by fr43nk** [comment]
What do you mean by **activity**?

**Comment by OpenNingia** [comment]
I use clearcase UCM that has activities:

https://www.ibm.com/support/knowledgecenter/SSSH27_8.0.1/com.ibm.rational.clearcase.dev.doc/topics/cc_dev/about_activity.htm

https://www.ibm.com/support/knowledgecenter/SSSH27_7.1.1/com.ibm.rational.clearcase.ccrc.help.doc/topics/t_ccteam_ucm_mkact.htm

**Comment by fr43nk** [comment]
I added the mkelem command to the untracked files context menu (#54)
When do you plan to publish a new version of the plugin?

**Comment by OpenNingia** [comment]
This week I'm sick at home 🤒 next week I'll try!
