### ISSUE TITLE
Changelog doesn't show inside VS Code extension display

### ISSUE THREAD

**Issue by BillDenton** [OpenNingia/vscode-clearcase#4]
The Changelog section in the extension display inside VS Code shows "No Changelog available".

**Comment by OpenNingia** [comment]
fixed in #351f33e54d3c71f48e63232300f023486daae109

**Comment by BillDenton** [comment]
Now showing OK. The ChangeLog only goes up to 1.4.0 and the ChangeLog is still at the bottom of Details pane.
