### ISSUE TITLE
Scm file command config

### ISSUE THREAD

**Issue by fr43nk** [OpenNingia/vscode-clearcase#47]
Maybe we can add a configuration date to let the user decide what command should be executed if he clicks on a checked out file. 
And by that also add an entry in the scm/resource/context depending what the user configured. Either `open resource` or `show the diff`

**Comment by OpenNingia** [comment]
I would prefer the "Open Resource" to be an entry on the right-click menu, similar to how the git scm behaves.

**Comment by fr43nk** [comment]
Ok. It’s the more easiest way

**Comment by OpenNingia** [comment]
On a second thought an option to select the default behavior wouldn't hurt. However I don't want to lose the "embedded diff" feature. So both of them should be present in the right-click menu.

About the settings I'm not sure how we can have a "dropdown-styled" option in VSCode, are you?

**Comment by fr43nk** [comment]
The context menu is an entry in the `package.json` There also exists an open resource command which can be used there. I can do that, but have no time right now.

**Comment by OpenNingia** [comment]
No pressure :)
