### ISSUE TITLE
Dose the extension support Clear Case Remote Client?

### ISSUE THREAD

**Issue by lonelyma1021** [OpenNingia/vscode-clearcase#55]
My project is useing Clear Case Remote Client. It's a pretty old version. I wanna know dose the extension support it?

**Comment by OpenNingia** [comment]
I never tried it. The extensions rely on the "cleartool" command line program. It should work if the tool is installed in your machine and it's in your PATH environment.

**Comment by OpenNingia** [comment]
Is this a duplicate of #57 ?

**Comment by fr43nk** [comment]
Hi @lonelyma1021,

is this still relevant for you? In the next version there will be support for the clearcase remote client.

Best regards

**Comment by fr43nk** [comment]
Support has been added in version 4.0.0.
