### ISSUE TITLE
Web-Views of ClearCase UCM are not recognized

### ISSUE THREAD

**Issue by bw1faeh0** [OpenNingia/vscode-clearcase#57]
I'm using Web-Views (ClearCase UCM) but unfortunately vscode-clearcase doesn't detect the files within this views as clearcase files.
Is there a way to support this kind of view?

Edit:
You can use the command `rcleartool` instead `cleartool`, see [this link](https://www.ibm.com/support/knowledgecenter/en/SSSH27_9.0.1/com.ibm.rational.clearcase.cc_ref.doc/topics/rcleartool.htm).
The available commands are listed [here](https://www.ibm.com/support/knowledgecenter/SSSH27_9.0.1/com.ibm.rational.clearcase.cc_ref.doc/topics/alphaintro.htm).
The presence of the `.copyarea.db` file could be used as indication, if you are in a web view.

**Comment by OpenNingia** [comment]
I won't be able to implement this because I'm not working with webviews and thus I'm not familiar with them. However I'm available to review a PR for this if you feel like submitting one.

**Comment by fr43nk** [comment]
@bw1faeh0 I am not familiar to web views, too. But as I understand you right, the difference is just the rcleartool command? If this is the only difference, I could give it a try. 
Where is this .copyarea.db located?

**Comment by fr43nk** [comment]
@bw1faeh0 could you please provide the output of the following command (if that works with rcleartool):
`rcleartool lsview -cview -long`

**Comment by bw1faeh0** [comment]
> @bw1faeh0 I am not familiar to web views, too. But as I understand you right, the difference is just the rcleartool command? If this is the only difference, I could give it a try.
> Where is this .copyarea.db located?

I have in every directory below the dir with the VOB name a .copyarea.db file
[VOBNAME]\.copyarea.db
[VOBNAME]\[DIR1]\.copyarea.db
[VOBNAME]\[DIR1]\[SUBDIR1]\.copyarea.db
[VOBNAME]\[DIR2]\.copyarea.db
[VOBNAME]\[DIR2]\[SUBDIR2]\.copyarea.db

and so on...

**Comment by bw1faeh0** [comment]
> [WEBVIEW_DIR]>rcleartool lsview -cview -long
Server-URL: https://ra-ccwan-bwg001.[COMPANYNAME].net/ccrc
CRCLI2031E Sitzung abgelaufen; erneute Authentifizierung erforderlich.
Anmelden bei Server "https://ra-ccwan-bwg001.[COMPANYNAME].net/ccrc".
Anmeldename: [USERNAME]
Kennwort:
Sie sind erfolgreich als "[USERNAME]" auf Server "https://ra-ccwan-bwg001.[COMPANYNAME].net/ccrc" angemeldet.
Tag: [MY_VIEWTAG]
  Global path: <no-gpath>
  Server host: DEBWGA99NC8SRV
  Region: [MY_REGION]
  Active: NO
  View tag uuid:61f240f0.926b430e.986d.d5:2a:e7:24:3f:75
View on host: DEBWGA99NC8SRV
View server access path: E:\Web_ccstore\[USERNAME]\[MY_VIEWTAG]\view.stg
View uuid: 61f240f0.926b430e.986d.d5:2a:e7:24:3f:75
View attributes: snapshot,ucmview,webview
View owner: [DOMAIN]\[USERNAME]

**Comment by fr43nk** [comment]
@bw1faeh0 Thank you for the output. You can try the plugin by downloading the release candidate version from
https://github.com/fr43nk/vscode-clearcase/releases/tag/2.4.1-rc.1
Download the vsix file and install it manually in vscode by selecting **"install from VSIX"** in the extension view.

**Comment by fr43nk** [comment]
@bw1faeh0 any news about the remote client working with this extension? Did you have time to give it a try?

**Comment by bw1faeh0** [comment]
Sorry, not yet.

**Comment by bw1faeh0** [comment]
> @bw1faeh0 Thank you for the output. You can try the plugin by downloading the release candidate version from
> https://github.com/fr43nk/vscode-clearcase/releases/tag/2.4.2-rc.1
> Download the vsix file and install it manually in vscode by selecting **"install from VSIX"** in the extension view.

I installed this version. I tried to modify a file within a webview. It seems, your plugin is using the cleartool  command, instead the rcleartool command. Error message:

```
Error checking out [Filename]. 
Not an object in a vob: [Filename].
Pathname provided did not resolv to a version object.
Not an object in a vob: [Filename].
```

**Comment by OpenNingia** [comment]
> Perhaps you should provide an option within the plugin to set the path of rcleartool.

This is a different feature request, could you please open a separate issue for that?

**Comment by fr43nk** [comment]
It seems like the view type detection didn't work. I will have a look at this.

**Comment by fr43nk** [comment]
@bw1faeh0 please have a look at the version

https://github.com/fr43nk/vscode-clearcase/releases/tag/2.4.2-rc.2

**Comment by bw1faeh0** [comment]
Same result

**Comment by fr43nk** [comment]
Hm, could you please post the information shown in the output channel **Clearcase SCM**?

**Comment by bw1faeh0** [comment]
```
lsview  
Cleartool error: Cleartool command error: spawn rcleartool ENOENT
Error while getting view type spawn rcleartool ENOENT
Creating a new cleartool instance and try again
lsview  
Cleartool error: Cleartool command lsview,-cview,-long exited with error code: -4058
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command lsview,-cview,-long exited with error code: 1
lsco    
catcs
catcs
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command catcs exited with error code: 1
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command catcs exited with error code: 1
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command lsco,-me,-cview,-short,-avobs exited with error code: 1
lsco    
catcs
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command lsco,-me,-cview,-short,-avobs exited with error code: 1
Cleartool error: Cleartool command catcs exited with error code: 1
lsco    
catcs
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command catcs exited with error code: 1
Cleartool error: Cleartool command lsco,-me,-cview,-short,-avobs exited with error code: 1
lsco    
catcs
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command lsco,-me,-cview,-short,-avobs exited with error code: 1
Cleartool error: Cleartool command catcs exited with error code: 1
lsco    
catcs
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command lsco,-me,-cview,-short,-avobs exited with error code: 1
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command catcs exited with error code: 1
```

**Comment by fr43nk** [comment]
It looks like the rcleartool command isn't found (first error).
So maybe it is easier to create a new configuration date as you suggested.
Exists the containing folder of the rcleartool command in your PATH environemnt?

**Comment by bw1faeh0** [comment]
I configured the path:
![image](https://user-images.githubusercontent.com/29235332/57440946-3d694900-7249-11e9-8f9f-0dee31ff7686.png)

The output of output channel Clearcase SCM is
`lsview`

Keep in mind, that rcleartool asks for server url, username and password on first use in a session. You should login first:

>rcleartool login [ –lna/me login-name ] [ –ser/ver server-url:port ] [ –pas/sword password ]
[ –proxy_lname proxy-login-name ] [ –proxy_password password ]

```
>rcleartool login -lname [username] -server https://[url]
Password: **********
>
```
See [https://www.ibm.com/support/knowledgecenter/en/SSSH27_8.0.1/com.ibm.rational.clearcase.cc_ref.doc/topics/rct_login.htm](url)

**Comment by fr43nk** [comment]
this sounds like it is working. The output of the ClearcaseSCM channel looks right (no error message).
Question is: Does it work as expected? Can you checkout files or see a version information in the status bar of the active window?
I can create a version where this login command is used first. But I doubt that it's working.
