### ISSUE TITLE
Consider bundling extension using webpack

### ISSUE THREAD

**Issue by OpenNingia** [OpenNingia/vscode-clearcase#63]
The extension has grown in size and now `vsce` ( the publishing tool ) warns about potential performance issues caused by the sheer amount of files.

```
> tsc -p ./

This extension consists of 244 separate files. For performance reasons, you should bundle your extension: https://aka.ms/vscode-bundle-extension
```

Microsoft released a guide to help us packaging the extension with Webpack:
https://code.visualstudio.com/api/working-with-extensions/bundling-extension

**Comment by fr43nk** [comment]
That‘s something I already thought about but always forgot to ask you about. 
If you want, I can try to get this to work. Should be a no brainer.

**Comment by OpenNingia** [comment]
Yes, great help! There is no hurry thou.

**Comment by fr43nk** [comment]
I think this one works (see #64)

**Comment by OpenNingia** [comment]
As I wrote in the PR review I cannot merge it because you downgraded the "vscode" package from 1.1.33 to 1.1.29.
