### ISSUE TITLE
Make cleartool executable configurable

### ISSUE THREAD

**Issue by fr43nk** [OpenNingia/vscode-clearcase#65]
To let the user decide which cleartool executable they want to use, there should be a configuration date for that.
This also could handle webviews (#55 and #57) on a workspace configuration layer.

**Comment by bw1faeh0** [comment]
Keep in mind, that rcleartool asks for server url, username and password on first use in a session. You should login first:

>rcleartool login [ –lna/me login-name ] [ –ser/ver server-url:port ] [ –pas/sword password ]
[ –proxy_lname proxy-login-name ] [ –proxy_password password ]

```
>rcleartool login -lname [username] -server https://[url]
Password: **********
>
```
See [https://www.ibm.com/support/knowledgecenter/en/SSSH27_8.0.1/com.ibm.rational.clearcase.cc_ref.doc/topics/rct_login.htm](url)

Password shall not be saved  in the configuration file but shall be asked on starting the session.

**Comment by fr43nk** [comment]
I never used rcleartool, so I wasn't aware of this. The doc says, every call to rcleartool requires such information.
I will add some more configuration data to provide username and url. The password will be saved as long as the active window exists. Would this be feasible for you?

**Comment by OpenNingia** [comment]
If that's the case then configuring the path of the executable isn't enough. We are going to need a `useRemoteClient: boolean` settings to support different behavior like asking for the login password.

Furthermore @fr43nk is correct, we're working in non-interactive mode; as such we need to provide the password on each command. 
The password will stay in memory for as long as needed. 
We should be extremely careful not to log the password along the executing command thou.

**Comment by bw1faeh0** [comment]
> Furthermore @fr43nk is correct, we're working in non-interactive mode; as such we need to provide the password on each command.

When I'm using the windows command prompt I use the non-interactive mode too. rcleartool asks for username and password only the first time, afterwards they are not needed, because the session is still active:

```
D:\ClearCase\>rcleartool lsview -server https://[URL]
Connection to server  "https://[URL]".
Username: [USERNAME]
Password: [PASSWORD]

You are successfully registered as "[USERNAME]" on server "https://[URL]".
  
  [Output of lsview]

```
Next non-interactive command:
```
D:\ClearCase\>rcleartool lsview -short -server https://[URL]

  [Output of lsview]

D:\ClearCase\>
```
As you see, the session seems to be saved in some kind of environmental variable.
(I translated the output from German to English, so maybe the keywords are not exactly the same)

**Comment by bw1faeh0** [comment]
> I will add some more configuration data to provide username and url. The password will be saved as long as the active window exists. Would this be feasible for you?

Perhaps you could add an option to save the password for the lazy ones ;) 

I always find it hard to store passwords in configuration files. Apart from the fact that they are changed every 90 days. I would have no problem typing the password once per session.

**Comment by fr43nk** [comment]
Please have a look at the new version
https://github.com/fr43nk/vscode-clearcase/releases/tag/2.4.2-rc.4

It will always use the login credentials on every command.
Please report how it works.

**Comment by bw1faeh0** [comment]
Sorry, this version does not work too. There is still the popup of **cleartool** (not detecting a vob). Output of Clearcase SCM is: `lsview`

My config looks like this:
vscode-clearcase.cleartoolExecutable: D:\Programs\IBM\RationalSDLC\ClearCase\RemoteClient\rcleartool.bat

vscode-clearcase.webviewAddress: https://[URL]

vscode-clearcase.webviewUsername: [my Username]

BTW:
It is not a Webview Address and a Webview Username. It is the Webserver Address and Webserver Username.

**Comment by fr43nk** [comment]
Please test the new version:
https://github.com/fr43nk/vscode-clearcase/releases/tag/2.4.2-rc.5
**Changed** configuration of username and address. Please have a look in your configuration.

**Comment by bw1faeh0** [comment]
```
login      
cleartool: Error: Unrecognized command: "login"

Error while login cleartool: Error: Unrecognized command: "login"
Cleartool error: Cleartool command login exited with error code: 1
lsco    
catcs
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command lsco exited with error code: 1
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command catcs exited with error code: 1
lsco    
catcs
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command lsco exited with error code: 1
Cleartool error: Cleartool command catcs exited with error code: 1
lsco    
catcs
cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

cleartool: Error: Cannot get view info for current view: not a ClearCase object.

Cleartool error: Cleartool command lsco exited with error code: 1
Cleartool error: Cleartool command catcs exited with error code: 1
```

Could you log the path of the (r)cleartool, you are using?

![image](https://user-images.githubusercontent.com/29235332/57512697-aebe0000-730c-11e9-84ff-43c5cb372933.png)
![image](https://user-images.githubusercontent.com/29235332/57512708-b8476800-730c-11e9-98b7-02479bf8d4de.png)
![image](https://user-images.githubusercontent.com/29235332/57512772-e2008f00-730c-11e9-9140-fa5a0434f194.png)

**Comment by fr43nk** [comment]
F*** I missed something. It always calls the cleartool command not your configured one. Sorry for that. I will correct that. Stay tuned.

**Comment by fr43nk** [comment]
Please download and install again the current rc-5
https://github.com/fr43nk/vscode-clearcase/releases/tag/2.4.2-rc.5

**Comment by bw1faeh0** [comment]
After Loading of VSC, I was asked for my PW. After that:
![image](https://user-images.githubusercontent.com/29235332/57517646-98697180-7317-11e9-8766-4d1751a49363.png)

(perhaps the timeout is to short?!?)

I tried to save a checked-in file, this was the result:
![image](https://user-images.githubusercontent.com/29235332/57517694-b931c700-7317-11e9-9365-e77ee5895d0e.png)

**Comment by fr43nk** [comment]
The checkout: Do you use the clearcase dialog? This is configurable.
The first message: I will have a look at it.

**Comment by bw1faeh0** [comment]
> The checkout: Do you use the clearcase dialog? This is configurable.
vscode-clearcase.useClearDlg = true;

When I use dynamic views I don't checkout via clearcase explorer. That is why I don't checkout the files before when using a webview, too. 
After canceling the dialog message above following additional output was generated:
```
catcs
lsco    
CRCLI2001E Nicht erkannte Option "-avobs".
Syntax: lsc/heckout | lsco [-l/ong | -s/hort ] [-brt/ype Verzweigungstypselektor] [-cvi/ew] [-me | -use/r Anmeldename] [-r/ecurse | -d/irectory] [Pfadname...]

Cleartool error: Cleartool command lsco exited with error code: 1
```

**Comment by fr43nk** [comment]
I am not quit sure, whether the dialog option does work the correct way in your scenario.
Try setting useClearDlg = false to use the rcleartool command you configured. May this works.
As you mentioned `unknown option "-avobs"` are there no vobs in a webview? There is also a configuration date for that. Look for the "Find checkouts Command Args" option and remove the -avobs parameter

**Comment by bw1faeh0** [comment]
Checking out seems to work somehow:

```
login      
catcs
catcs
CRCLI2014E Sie sind bereits bei Server "https://[URL]" angemeldet.

Cleartool error: Cleartool command login exited with error code: 1
lsco   
catcs
co   
co   
catcs
catcs
CRCLI2059E Element "d:\ClearCase\[...]\version.h" wurde bereits in Ansicht "[View Name]" ausgecheckt.

Cleartool error: Cleartool command co exited with error code: 1
catcs
catcs
```
(I restarted VSC before this test)

**Comment by fr43nk** [comment]
Sounds promising somehow :smile: 
What makes me wonder: there are two `co` entries. I suppose you only started checkout once, did you?
Does the list of checkedout files work in the SCM view?

**Comment by bw1faeh0** [comment]
> Does the list of checkedout files work in the SCM view?

STRG J + STRG F brings up a ClearCase Dialog Window to find checkouts:
![image](https://user-images.githubusercontent.com/29235332/57598284-eb7b3880-7552-11e9-8bc3-77794b947248.png)

But it does not help, because it is not a dynamic view:
![image](https://user-images.githubusercontent.com/29235332/57598320-11084200-7553-11e9-9c7d-7e934ddd85db.png)

Does rcleartool provide an equivalent?

**Comment by fr43nk** [comment]
> STRG J + STRG F brings up a ClearCase Dialog Window to find checkouts:
I meant this as SCM view:
![grafik](https://user-images.githubusercontent.com/3279247/57599394-ce486900-7556-11e9-8a0c-90379d6a6201.png)

There are all checked out files listed in this section and if you like view private files, too.
Are files listed there?

**Comment by bw1faeh0** [comment]
Sorry, Clearcase is not recognized as SCM:
![image](https://user-images.githubusercontent.com/29235332/57614531-c8b04a80-7579-11e9-80d9-6ed8752eb615.png)

**Comment by fr43nk** [comment]
Please have a look again at the latest pre release version
https://github.com/fr43nk/vscode-clearcase/releases/tag/2.4.2-rc.5
Maybe uninstall the existing extension first.

Now there should be no error message saying "already logged in". And with that the SCM view should recognize a scm provider. (I hope :crossed_fingers:)

Did you change the configuration ```vscode-clearcase.useClearDlg = true;``` to ```vscode-clearcase.useClearDlg = false;```?
If so, you have the ability to checkout on save without any interruption. The successful checkout should be visible in the statusbar of the current window. Saying something like ```[/main/version1/CHECKEDOUT]```

**Comment by bw1faeh0** [comment]
I removed the extension and installed rc.5 again. `vscode-clearcase.useClearDlg` is `false`.

Checking SCM:
![image](https://user-images.githubusercontent.com/29235332/57620717-e7b6d880-7589-11e9-80aa-eb6545856114.png)

![image](https://user-images.githubusercontent.com/29235332/57620729-f00f1380-7589-11e9-822e-65da2f284e53.png)
![image](https://user-images.githubusercontent.com/29235332/57620741-f9987b80-7589-11e9-85ce-59805de2d843.png)

(now i modified the file and hit strg +s. I didn't set a checkout comment)

![image](https://user-images.githubusercontent.com/29235332/57620913-6c095b80-758a-11e9-90bf-7e6067e8523a.png)

![image](https://user-images.githubusercontent.com/29235332/57620928-71ff3c80-758a-11e9-9e9b-6f353d540bba.png)

Checkout seems to work. Now trying to check in:

![image](https://user-images.githubusercontent.com/29235332/57621116-efc34800-758a-11e9-9847-3d5d14b100d1.png)

![image](https://user-images.githubusercontent.com/29235332/57621172-11bcca80-758b-11e9-889e-0e852de1de9d.png)

File is still checked out...

**Comment by fr43nk** [comment]
It seams there where still problems handling the login.
If you are still willing to test, then please use the new version.
**Note**: You can have a look in your user home directory, there should be a folder 
```
.vscode\extensions
```
Maybe there are a lot of different versions of this extension still existing. They can be deleted
https://github.com/fr43nk/vscode-clearcase/releases/tag/2.4.2-rc.6

**Comment by bw1faeh0** [comment]
I removed the dir of the extension within .vscode\extensions. After re-installation I was asked for my pwd. the plugin managed to login:
![image](https://user-images.githubusercontent.com/29235332/57674773-68281880-7620-11e9-80c2-8154841ff817.png)

After that I restarted VS Code (just do get a clean starting point). I was asked for the pwd again. I edited my test file, hit strg + s, it took some time, but at the end it looks like this:
![image](https://user-images.githubusercontent.com/29235332/57674845-9efe2e80-7620-11e9-8155-92f22273fa06.png)
As you see, I was still logged in even after closing VS Code. But anyway, checkout works:
![image](https://user-images.githubusercontent.com/29235332/57674894-bfc68400-7620-11e9-95f8-59d110f1f56a.png)
Now I hit STRG J + STRG + I to checkin. It took some time (rcleartool is very slow):
```
catcs
lsco   
clearcase, stdout: D:\ClearCase\bw1faeh0_GPMG_Develop_CF\EFZM_Dev\GMPG\inc\version.h@@\main\GmPg_Int\GPMG_Develop_CF\CHECKEDOUT von \main\GmPg_Int\GPMG_Develop_CF\10  Regel: CHECKEDOUT

ci
lsco   
catcs
```
![image](https://user-images.githubusercontent.com/29235332/57675149-64e15c80-7621-11e9-91ea-984d55c65d99.png)

So it looks like the the basics are working. 

But I see open points:
- rcleartool checkin and checkout takes very long time (30..40 sec). Is it possible to create some kind of popup to notify the user to wait?
- the setup of the plugin should be project depended. In my case I have projects using basic clearcase with the cleartool command and projects using webviews and rcleartool. Switching the extension config is inconvenient

Perhaps you can drop me a line for further debugging and testing (if you like): webmaster@mail.flaemig42.de

**Comment by fr43nk** [comment]
Looks great. Here are my questions:
* does rcleartool also take such a long time if used outside vscode?
* is the SCM view working? Are there any checkedout files listed?

Project depended configuration already exists in vscode. Just Store your current workspace `Save workspace as...`. After that you can easily set configurations via the settings ui.

**Comment by fr43nk** [comment]
@bw1faeh0 are you still interested in using the plugin with remote clearcase client? I know it was a long time since the last change, but chances are good that remote clearcase support gets into the extension.
