### ISSUE TITLE
Doesn't track checkouts not made in session

### ISSUE THREAD

**Issue by BillDenton** [OpenNingia/vscode-clearcase#69]
Any checkouts that are made externally or before the editor was opened or before a reload window are not shown. Using the refresh checkouts button doesn't help. It used to work and pick up existing checkouts and those made during the editor session.

Name: Unofficial ClearCase SCM Commands
Id: openningia.vscode-clearcase
Description: Unofficial support for IBM Rational ClearCase most common commands
Version: 2.4.3
Publisher: OpenNingia
VS Marketplace Link: https://marketplace.visualstudio.com/items?itemName=OpenNingia.vscode-clearcase

Version: 1.34.0 (user setup)
Commit: a622c65b2c713c890fcf4fbf07cf34049d5fe758
Date: 2019-05-15T21:59:37.030Z
Electron: 3.1.8
Chrome: 66.0.3359.181
Node.js: 10.2.0
V8: 6.6.346.32
OS: Windows_NT x64 10.0.17134

**Comment by fr43nk** [comment]
What kind of view is this?
The checkedout list is refreshed always on editor window change. So you should see all checkedout files in the SMC view.
Could you please share the output of plugin. To do this open the internal terminal. In the upper left of this window, there is a menu entry called *OUTPUT*. After that you can select the output by selecting *Clearcase SCM* in the list.
![grafik](https://user-images.githubusercontent.com/3279247/59416547-d7cb2800-8dc5-11e9-9ade-797afc37a77b.png)

**Comment by OpenNingia** [comment]
@BillDenton you can personalize the find checkout command.

I, for example use: `-me -cview -short -all` and it works better in my views.


```json
"vscode-clearcase.findCheckoutsCommandArgs": "-me -cview -short -all"
```
