### ISSUE TITLE
How can I find "A valid ClearCase installation within the system's PATH."

### ISSUE THREAD

**Issue by hikidd** [OpenNingia/vscode-clearcase#81]
I'm using ClearCase Remote Client to connect server to use.
I enter a url to connect clear case server, then use clear case.

And I printed my system path, but found nothing except a lot of "IBM\Rational\Shared\SA\***.dll" 😢 
How can I find A valid ClearCase installation?

Thanks! 😄

**Comment by OpenNingia** [comment]
I don't know if this extension will work on your system. This extension leverage the `cleartool` command line client provided by the installation of IBM Rational Clearcase. If your setup does not include this tool then the extension will not work :/

**Comment by almtoolbox** [comment]
If you support 'rcleartool' it might work

**Comment by OpenNingia** [comment]
You can configure the executable path in the settings, someone tried to make `rcleartool` works here:
https://github.com/OpenNingia/vscode-clearcase/issues/65
