### ISSUE TITLE
CC options no longer show up

### ISSUE THREAD

**Issue by chelCcat** [OpenNingia/vscode-clearcase#88]
We have written the needed data into your clipboard because it was too large to send. Please paste.

**Comment by chelCcat** [comment]
Issue Type: <b>Bug</b>

CC options found when R-CLICKing a file: vtree, checkin, checkout, etc) & file saving help (automatically checkout the file) only show up when opening a directory... but they don't show up at all after the latest VS Code update.



Extension version: 2.7.0
VS Code version: Code 1.63.2 (899d46d82c4c95423fb7e10e68eba52050e30ba3, 2021-12-15T09:40:02.816Z)
OS version: Windows_NT x64 10.0.19043
Restricted Mode: No

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Xeon(R) Gold 6134 CPU @ 3.20GHz (8 x 3200)|
|GPU Status|2d_canvas: unavailable_software<br>gpu_compositing: disabled_software<br>multiple_raster_threads: enabled_on<br>oop_rasterization: disabled_off<br>opengl: disabled_off<br>rasterization: disabled_software<br>skia_renderer: enabled_on<br>video_decode: disabled_software<br>vulkan: disabled_off<br>webgl: unavailable_software<br>webgl2: unavailable_software|
|Load (avg)|undefined|
|Memory (System)|32.00GB (20.24GB free)|
|Process Argv|--crash-reporter-id e8785ac2-1f9d-4bca-889a-36a815dc4346|
|Screen Reader|no|
|VM|25%|
</details><details>
<summary>A/B Experiments</summary>

```
vsliv368:30146709
vsreu685:30147344
python383cf:30185419
vspor879:30202332
vspor708:30202333
vspor363:30204092
pythonvspyl392cf:30425750
pythontb:30283811
pythonvspyt551cf:30345471
pythonptprofiler:30281270
vsdfh931:30280409
vshan820:30294714
vstes263:30335439
pythondataviewer:30285071
vscod805cf:30301675
pythonvspyt200:30340761
binariesv615:30325510
bridge0708:30335490
bridge0723:30353136
vsaa593cf:30376535
vsc1dst:30428979
pythonvs932:30410667
vscop940:30404999
vsrem710:30416614
vscop841:30430977

```

</details>

**Comment by OpenNingia** [comment]
Can you verify if this is fixed with the last version?

**Comment by chelCcat** [comment]
Hi there, thanks for getting back to me.

I no longer work at the company that used this VCM. Sorry, I am not able to
test anything. But I can tell you I did not have the issue at the time I
left 3 weeks ago



Thanks!

Chelsea DAlessandro
404.428.5136
