### ISSUE TITLE
Clearcase statusbar information

### ISSUE THREAD

**Issue by fr43nk** [OpenNingia/vscode-clearcase#9]
I'm thinking about adding a statusbar feature.
There could be the version information of the current file displayed in the statusbar.

The style could be something like: [/branch1/branch2/LATEST]

I think this should be easy to accomplish with an 
```
cleartool ls ${file} -short.
```
What do you think?

**Comment by BillDenton** [comment]
Possible but it could occupy a lot of space on the status bar. Would need to be configurable.

**Comment by OpenNingia** [comment]
On my system I need to write `cleartool ls -short ${file}`, seems the order of the switches is important.
I like the status bar idea, but as @BillDenton said it should be configurable ( as an opt-off, since is a nice feature and should be discoverable :+1:  ).

**Comment by BillDenton** [comment]
I tested under Windows and the order is `cleartool ls -short ${file}`.
